#Honor Pledge: I pledge that I have neither
#given nor received any undue help on this assignment.
#
#strangni
#
#CS 240 - Assignment 5 - A Healthy Dose of Inheritance
#Created by: Nicholas Strange

Driver.class: Driver.java Sort.class BubbleSort.class InsertionSort.class
	javac Driver.java

BubbleSort.class: BubbleSort.java
	javac BubbleSort.java

InsertionSort.class: InsertionSort.java
	javac InsertionSort.java

Sort.class: Sort.java
	javac Sort.java

clean:
	-rm *.class

run: Driver.class
	java Driver
